### ISSUE TITLE
Some comments re Rhai packages

### ISSUE THREAD

**Issue by schungx** [alvinhochun/wasm-project-template#2]
https://github.com/alvinhochun/wasm-project-template/blob/rhai-demo/wasm-module/src/scripting.rs#L10-11

You don't need these lines:

```rust
engine.load_package(ArithmeticPackage::new().get());
engine.load_package(LogicPackage::new().get());
```

`Engine::new()` already includes these packages.  You don't have to load them once again and it'll be better on speed.

If you want to _only_ include these packages and nothing else, you should use `Engine::new_raw()`.  This way, the WASM size will be significantly reduced because code from non-loaded packages will not be included.

**Comment by schungx** [comment]
Not sure if these in `Cargo.toml` will reduce the WASM size:

```toml
lto = "fat"
codegen-units = 1
```

**Comment by alvinhochun** [comment]
Fat LTO does cut down about 12KB in raw size, but it is currently a bit broken on Rust stable.

**Comment by schungx** [comment]
Well, how about `lto = true`?

**Comment by alvinhochun** [comment]
Same thing.

**Comment by schungx** [comment]
I've been using LTO for quite a while now (well, actually months), and it has been stable so far...

Really needed this for dead-code removal... without it the binaries tend to be huge.

**Comment by alvinhochun** [comment]
> I've been using LTO for quite a while now (well, actually months), and it has been stable so far...

No, it's an issue specific to Wasm: https://github.com/rust-lang/rust/issues/72758
